<?php
/*
South African Theological Seminary
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_satsmail_get_settings' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_settings',
        'description' => 'Get site settings.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_strings' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_strings',
        'description' => 'Get language strings.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_preferences' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_preferences',
        'description' => 'Get user preferences.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_set_preferences' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_preferences',
        'description' => 'Set user preferences.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_get_courses' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_courses',
        'description' => 'Get user courses.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_labels' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_labels',
        'description' => 'Get user labels.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_count_messages' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'count_messages',
        'description' => 'Count the number of messages.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_search_messages' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'search_messages',
        'description' => 'Search messages.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_message',
        'description' => 'Get the contents of a message.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_view_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'view_message',
        'description' => 'Marks a message as read and triggers a viewed event.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_set_unread' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_unread',
        'description' => 'Sets the unread status of a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_set_starred' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_starred',
        'description' => 'Sets the starred status of a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_set_deleted' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_deleted',
        'description' => 'Sets the deleted status of a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_set_archived' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_archived',
        'description' => 'Sets the archived status of a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_create_label' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'create_label',
        'description' => 'Creates a new label.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_update_label' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'update_label',
        'description' => 'Updates a label.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_delete_label' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'delete_label',
        'description' => 'Deletes a label.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_set_labels' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'set_labels',
        'description' => 'Sets the labels of a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_empty_trash' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'empty_trash',
        'description' => 'Empties the trash.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_get_roles' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_roles',
        'description' => 'Get course roles.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_groups' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_groups',
        'description' => 'Get course groups.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_search_users' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'search_users',
        'description' => 'Search course users.',
        'type' => 'read',
        'ajax' => true,
    ],
    'local_satsmail_get_message_form' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'get_message_form',
        'description' => 'Creates a forwarded message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_create_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'create_message',
        'description' => 'Creates a new message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_reply_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'reply_message',
        'description' => 'Creates a message reply.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_forward_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'forward_message',
        'description' => 'Creates a forwarded message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_update_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'update_message',
        'description' => 'Updates a message.',
        'type' => 'write',
        'ajax' => true,
    ],
    'local_satsmail_send_message' => [
        'classname' => 'local_satsmail\\external',
        'methodname' => 'send_message',
        'description' => 'Sends a message.',
        'type' => 'write',
        'ajax' => true,
    ],
];

